"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { formatTime, median, postJson, secondsFor, useClock, useTrainingData } from "./data";
import { Loading } from "./Loading";

export function Dashboard(){const {data,error,loading,refresh}=useTrainingData();const [date,setDate]=useState("");const [saving,setSaving]=useState(false);const now=useClock(30000);
  const metrics=useMemo(()=>{if(!data)return null;const completed=data.attempts.filter(a=>a.status==="completed");const unique=new Set(completed.map(a=>a.problem_id));const totals=new Map<string,number>();const itemTotals=new Map<string,number>();let totalSeconds=0;for(const s of data.timeSegments){const seconds=secondsFor(s,now);totalSeconds+=seconds;totals.set(s.attempt_id,(totals.get(s.attempt_id)||0)+seconds);if(s.problem_part_id)itemTotals.set(`${s.attempt_id}:${s.problem_part_id}`,(itemTotals.get(`${s.attempt_id}:${s.problem_part_id}`)||0)+seconds);}const questionTimes=completed.map(a=>totals.get(a.id)||0).filter(Boolean);const cutoff7=now-7*86400000,cutoff30=now-30*86400000;const recent=(cutoff:number)=>completed.filter(a=>a.finished_at&&Date.parse(a.finished_at)>=cutoff).length;
    const tags=data.tags.map(tag=>{const problemIds=new Set(data.problemTags.filter(pt=>pt.tag_id===tag.id).map(pt=>pt.problem_id));const completedProblems=new Set(completed.filter(a=>problemIds.has(a.problem_id)).map(a=>a.problem_id));const partIds=new Set(data.problemParts.filter(p=>problemIds.has(p.problem_id)).map(p=>p.id));const samples=[...itemTotals].filter(([key])=>partIds.has(Number(key.split(":")[1]))).map(([,v])=>v);return{name:tag.name,questions:completedProblems.size,items:samples.length,median:median(samples)};}).filter(t=>t.questions||t.items).sort((a,b)=>b.items-a.items);
    const volume=Array.from({length:14},(_,i)=>{const d=new Date(now-(13-i)*86400000);const key=d.toISOString().slice(0,10);return{key,label:d.toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"}),count:completed.filter(a=>a.finished_at?.slice(0,10)===key).length};});return{completed,unique:unique.size,itemCount:itemTotals.size,totalSeconds,medianItem:median([...itemTotals.values()]),medianQuestion:median(questionTimes),recent7:recent(cutoff7),recent30:recent(cutoff30),tags,volume};},[data,now]);
  if(loading||!data||!metrics||!now)return <Loading error={error}/>;const configured=data.settings.tbf_date;const days=configured?Math.ceil((Date.parse(`${configured}T23:59:59`)-now)/86400000):null;const maxVolume=Math.max(1,...metrics.volume.map(v=>v.count));
  async function saveDate(){setSaving(true);try{await postJson("/api/settings",{tbfDate:date||configured});await refresh();setDate("");}finally{setSaving(false);}}
  return <><section className="hero"><div><p className="eyebrow">Preparação olímpica</p><h1>Visão objetiva do treino</h1><p className="muted">Questões isoladas, tempo por item e simulados — sem score artificial.</p></div><div className="countdown"><span>TBF</span><strong>{days==null?"—":days<0?"já ocorreu":`${days} dias`}</strong><div className="inline-form"><input aria-label="Data do TBF" type="date" value={date||configured||""} onChange={e=>setDate(e.target.value)}/><button className="button ghost" onClick={saveDate} disabled={saving}>Salvar</button></div></div></section>
  {data.attempts.some(a=>a.status==="in_progress")&&<section className="notice"><strong>Tentativa em andamento</strong>{data.attempts.filter(a=>a.status==="in_progress").map(a=>{const p=data.problems.find(p=>p.id===a.problem_id);return <Link key={a.id} href={`/questao/${a.problem_id}`}>{p?.code} · {p?.title} →</Link>})}</section>}
  <section className="metric-grid"><Metric label="Questões únicas" value={String(metrics.unique)}/><Metric label="Tentativas" value={String(data.attempts.length)}/><Metric label="Itens trabalhados" value={String(metrics.itemCount)}/><Metric label="Tempo resolvendo" value={formatTime(metrics.totalSeconds)}/><Metric label="Últimos 7 dias" value={String(metrics.recent7)}/><Metric label="Últimos 30 dias" value={String(metrics.recent30)}/><Metric label="Mediana por item" value={metrics.medianItem==null?"—":formatTime(metrics.medianItem)}/><Metric label="Mediana por questão" value={metrics.medianQuestion==null?"—":formatTime(metrics.medianQuestion)}/></section>
  <section className="two-col"><div className="panel"><div className="section-head"><div><p className="eyebrow">Volume</p><h2>Questões concluídas</h2></div><span className="muted">14 dias</span></div><div className="bar-chart">{metrics.volume.map(v=><div className="bar-column" key={v.key}><span>{v.count||""}</span><div style={{height:`${Math.max(4,(v.count/maxVolume)*100)}%`}}/><small>{v.label}</small></div>)}</div></div><div className="panel"><div className="section-head"><div><p className="eyebrow">Simulados</p><h2>Notas ao longo do tempo</h2></div><Link href="/simulados">Cadastrar</Link></div>{data.mockExams.length?<div className="score-list">{[...data.mockExams].reverse().map(s=><div key={s.id}><span>{new Date(`${s.date}T12:00:00`).toLocaleDateString("pt-BR")}</span><strong>{s.total_score}/{s.max_score}</strong><meter min="0" max="100" value={(s.total_score/s.max_score)*100}/></div>)}</div>:<p className="muted">Nenhum simulado cadastrado.</p>}</div></section>
  <section className="panel"><div className="section-head"><div><p className="eyebrow">Conteúdos</p><h2>Prática por tag</h2></div><span className="muted">Tempo não implica fraqueza.</span></div>{metrics.tags.length?<div className="table-wrap"><table><thead><tr><th>Tag</th><th>Questões</th><th>Itens (n)</th><th>Mediana/item</th></tr></thead><tbody>{metrics.tags.map(t=><tr key={t.name}><td>{t.name}</td><td>{t.questions}</td><td>{t.items}</td><td>{t.median==null?"—":formatTime(t.median)}</td></tr>)}</tbody></table></div>:<p className="muted">As métricas por tag aparecerão após o primeiro treino.</p>}</section>
  <section className="panel export-panel"><div><p className="eyebrow">Dados brutos</p><h2>Exportar para análise</h2><p className="muted">O JSON reconstrói catálogo, tentativas, segmentos e simulados.</p></div><div className="actions"><a className="button" href="/api/export/json">JSON completo</a><a className="button ghost" href="/api/export/csv?table=attempts">CSV tentativas</a><a className="button ghost" href="/api/export/csv?table=segments">CSV segmentos</a><a className="button ghost" href="/api/export/csv?table=mock_scores">CSV notas</a></div></section></>}
function Metric({label,value}:{label:string;value:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
