"use client";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { formatTime, postJson, secondsFor, useClock, useTrainingData } from "./data";
import { Loading } from "./Loading";

export function ProblemWorkspace(){const params=useParams<{id:string}>();const problemId=Number(params.id);const {data,error,loading,refresh}=useTrainingData();const now=useClock();const [busy,setBusy]=useState(false);const [minimized,setMinimized]=useState(false);
  const problem=data?.problems.find(p=>p.id===problemId);const parts=useMemo(()=>data?.problemParts.filter(p=>p.problem_id===problemId)||[],[data,problemId]);const attempts=useMemo(()=>data?.attempts.filter(a=>a.problem_id===problemId)||[],[data,problemId]);const active=attempts.find(a=>a.status==="in_progress");const segments=useMemo(()=>data?.timeSegments.filter(s=>s.attempt_id===active?.id)||[],[data,active]);const total=segments.reduce((sum,s)=>sum+secondsFor(s,now),0);const initial=segments.filter(s=>s.state==="initial_reading").reduce((sum,s)=>sum+secondsFor(s,now),0);const partTimes=new Map<number,number>();for(const s of segments)if(s.problem_part_id)partTimes.set(s.problem_part_id,(partTimes.get(s.problem_part_id)||0)+secondsFor(s,now));
  const act=useCallback(async(action:string,partId?:number)=>{if(!active)return;setBusy(true);try{await postJson(`/api/attempts/${active.id}/timer`,{action,partId});await refresh();}finally{setBusy(false)}},[active,refresh]);
  useEffect(()=>{function key(e:KeyboardEvent){if(!active||busy||["INPUT","TEXTAREA","SELECT"].includes((e.target as HTMLElement).tagName))return;if(e.code==="KeyM"){setMinimized(v=>!v);return}if(e.code==="KeyP"||e.code==="Space"){e.preventDefault();void act(active.current_state==="paused"?"resume":"pause");return}const n=Number(e.key);if(n>=1&&n<=9&&parts[n-1])void act("select_part",parts[n-1].id)}window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[active,busy,parts,act]);
  if(loading||!data)return <Loading error={error}/>;if(!problem)return <section className="empty"><strong>Questão não encontrada</strong></section>;const tags=data.problemTags.filter(pt=>pt.problem_id===problem.id).map(pt=>data.tags.find(t=>t.id===pt.tag_id)?.name).filter(Boolean);
  async function start(){setBusy(true);try{await postJson("/api/attempts",{problemId});await refresh();}finally{setBusy(false)}}
  async function finish(){if(!active||!confirm("Finalizar esta questão? Ela passará a contar como concluída."))return;await act("finish")}
  return <><section className="problem-header"><div><p className="eyebrow">{data.exams.find(e=>e.id===problem.exam_id)?.code} · {problem.kind==="experimental"?"Experimental":"Teórica"}</p><h1><span>{problem.code}</span> {problem.title}</h1><div className="tag-line">{tags.map(tag=><em key={tag}>{tag}</em>)}</div></div><div className="source-links"><a href={problem.statement_url||problem.source_url} target="_blank" rel="noreferrer">Enunciado ↗</a>{problem.solution_url&&<a href={problem.solution_url} target="_blank" rel="noreferrer">Solução ↗</a>}{problem.marking_scheme_url&&<a href={problem.marking_scheme_url} target="_blank" rel="noreferrer">Pontuação ↗</a>}</div></section>
  <div className="workspace"><section className="panel parts-panel"><div className="section-head"><div><p className="eyebrow">Itens</p><h2>Selecione o que está trabalhando</h2></div><span className="muted">A atividade vem do timer.</span></div><div className="part-list">{parts.map((part,index)=><button disabled={!active||busy} className={`part-card ${active?.active_part_id===part.id&&active.current_state!=="paused"?"active":""}`} onClick={()=>act("select_part",part.id)} key={part.id}><span className="part-code">{part.code}<small>{index<9?index+1:""}</small></span><span className="part-prompt">{part.prompt_text||"Item sem descrição importada"}</span><strong>{formatTime(partTimes.get(part.id)||0)}</strong></button>)}</div></section>
  <aside className={`timer-card ${minimized?"minimized":""}`}><div className="timer-top"><div><span className="timer-state">{!active?"Sem tentativa":active.current_state==="paused"?"Pausado":active.current_state==="initial_reading"?"Leitura inicial":`Item ${parts.find(p=>p.id===active.active_part_id)?.code||""}`}</span><strong className="timer-total">{formatTime(total)}</strong></div>{active&&<button className="icon-button" onClick={()=>setMinimized(v=>!v)} aria-label={minimized?"Expandir cronômetro":"Minimizar cronômetro"}>{minimized?"□":"—"}</button>}</div>{!minimized&&<>{active?<><dl className="timer-details"><div><dt>Leitura inicial</dt><dd>{formatTime(initial)}</dd></div><div><dt>Itens ativos</dt><dd>{formatTime(total-initial)}</dd></div></dl><div className="timer-actions"><button className="button" disabled={busy} onClick={()=>act(active.current_state==="paused"?"resume":"pause")}>{active.current_state==="paused"?"Continuar":"Pausar"}</button><button className="button danger" disabled={busy} onClick={finish}>FINALIZAR QUESTÃO</button></div><p className="shortcuts"><kbd>Espaço</kbd>/<kbd>P</kbd> pausa · <kbd>1–9</kbd> item · <kbd>M</kbd> minimiza</p></>:<button className="button wide" disabled={busy} onClick={start}>{attempts.length?"Refazer — nova tentativa":"Iniciar tentativa"}</button>}</>}</aside></div>
  <section className="panel history"><div className="section-head"><h2>Dados pessoais desta questão</h2><span>{attempts.length} tentativa(s)</span></div>{attempts.length?<div className="history-list">{attempts.map(a=>{const secs=data.timeSegments.filter(s=>s.attempt_id===a.id).reduce((sum,s)=>sum+secondsFor(s,now),0);return <div key={a.id}><span>{a.status==="completed"?"Concluída":"Em andamento"}</span><strong>{formatTime(secs)}</strong><small>{new Date(a.started_at).toLocaleString("pt-BR")}</small></div>})}</div>:<p className="muted">Ainda não há treino registrado.</p>}</section></>}
