import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const read=(path)=>readFile(new URL(`../${path}`,import.meta.url),"utf8");
test("keeps the dashboard essential and exports everything once",async()=>{const [dashboard,exportRoute]=await Promise.all([read("app/components/Dashboard.tsx"),read("app/api/export/json/route.ts")]);assert.match(dashboard,/Questões resolvidas/);assert.match(dashboard,/Questões resolvidas por dia/);assert.match(dashboard,/questions === 1 \? "one" : questions === 2 \? "two" : questions === 3 \? "three" : "four"/);assert.match(dashboard,/\["four","4\+"\]/);assert.match(dashboard,/Questões resolvidas por tag/);assert.match(dashboard,/STUDY_START = new Date\(2026, 4, 2\)/);assert.match(dashboard,/TBF_DATE = new Date\(2027, 1, 20\)/);assert.match(dashboard,/Baixar todos os dados/);assert.doesNotMatch(dashboard,/Tempo resolvendo por dia|Últimos 7 dias|Últimos 30 dias|\/api\/export\/csv|Data do TBF/);assert.match(exportRoute,/readFullExportData/)});
test("separates X and Y with descending years and compact problem states",async()=>{const catalog=await read("app/components/Catalog.tsx");assert.match(catalog,/\["X","Y"\]/);assert.match(catalog,/\(b\.year\|\|0\)-\(a\.year\|\|0\)/);assert.match(catalog,/compareProblemCodes/);assert.match(catalog,/em andamento/);assert.match(catalog,/completed===1\?"concluída"/);assert.match(catalog,/completed>1\?`\$\{completed\}× concluída`/);assert.doesNotMatch(catalog,/Abrir|Origem|Série \{seriesCode\}|exam\.code/)});
test("replaces the starter with the training product shell",async()=>{const [layout,page,css,pkg]=await Promise.all([read("app/layout.tsx"),read("app/page.tsx"),read("app/globals.css"),read("package.json")]);assert.match(layout,/Treino de Física/);assert.match(layout,/Catálogo XY/);assert.match(layout,/Entrar com ChatGPT/);assert.match(layout,/chatGPTSignOutPath/);assert.match(page,/Dashboard/);assert.match(css,/timer-card/);assert.doesNotMatch(`${layout}${page}${pkg}`,/codex-preview|react-loading-skeleton|SkeletonPreview/)});
test("contains the complete MVP routes",async()=>{const files=await Promise.all(["app/components/ProblemWorkspace.tsx","app/components/MockExams.tsx","app/components/Laboratory.tsx","app/api/attempts/route.ts","app/api/attempts/[id]/timer/route.ts","app/api/attempts/[id]/hints/route.ts","app/api/export/json/route.ts","app/api/export/csv/route.ts"].map(read));const source=files.join("\n");for(const marker of ["item_active","FINALIZAR QUESTÃO","problemScores","timeSegments","experiments","text/csv","Pedir hint","user_hint_events"])assert.match(source,new RegExp(marker));assert.doesNotMatch(source,/mastery|streak/i)});
test("clicking an item in the statement creates or resumes an attempt and starts its timer",async()=>{const [workspace,attempts,timer,data,math]=await Promise.all([read("app/components/ProblemWorkspace.tsx"),read("app/api/attempts/route.ts"),read("app/api/attempts/[id]/timer/route.ts"),read("app/components/data.ts"),read("app/components/MathContent.tsx")]);assert.match(attempts,/'in_progress','paused'/);assert.doesNotMatch(attempts,/INSERT INTO user_time_segments/);assert.match(timer,/Selecione um item para começar/);assert.match(workspace,/postJson\("\/api\/attempts",\{problemId\}\)/);assert.match(workspace,/onPartClick=\{selectPart\}/);assert.match(workspace,/refresh\(\{silent:true\}\)/);assert.match(math,/statement-part-button/);assert.match(math,/root\.innerHTML = normalizeMathMarkup\(html\)/);assert.match(math,/renderMathInElement/);assert.match(data,/options\?:\{silent\?:boolean\}/);assert.doesNotMatch(workspace,/parts-panel|part-card|Selecione o que está trabalhando|Página original|Leitura inicial|1–9|index < 9/)});
test("keeps problem reading wide, renders math deterministically and offers brown noise",async()=>{const [workspace,math,units,renderer,route,css,dashboard]=await Promise.all([read("app/components/ProblemWorkspace.tsx"),read("app/components/MathContent.tsx"),read("app/lib/physics-math.mjs"),read("app/lib/render-statement-math.mjs"),read("app/api/problems/[id]/statement/route.ts"),read("app/globals.css"),read("app/components/Dashboard.tsx")]);assert.match(math,/normalizeMathMarkup/);assert.match(math,/preProcess:prepareMath/);assert.match(units,/formula\.replace\(\/<br/);assert.match(units,/"Ом":"\\\\Omega"/);assert.match(renderer,/katex\.renderToString/);assert.match(route,/renderStatementMath\(statementHtml\)/);assert.match(workspace,/createBuffer\(2,context\.sampleRate\*seconds/);assert.match(workspace,/brown noise/i);assert.match(workspace,/data\.canUseAi && <aside/);assert.match(css,/body:has\(\.problem-page\) \.shell\{max-width:none/);assert.match(css,/font-family:"Times New Roman",Times,serif/);assert.doesNotMatch(css,/font-family:Georgia/);assert.doesNotMatch(workspace,/Tradução automática|>Português</);assert.doesNotMatch(dashboard,/<small>hoje<\/small>/)});
test("keeps study controls discreet and highlights only real part headings",async()=>{const [workspace,timer,math,css]=await Promise.all([read("app/components/ProblemWorkspace.tsx"),read("app/api/attempts/[id]/timer/route.ts"),read("app/components/MathContent.tsx"),read("app/globals.css")]);assert.match(workspace,/Descartar somente o intervalo atual/);assert.match(workspace,/className="timer-discard"/);assert.match(workspace,/aria-label=\{brownNoise \? "Parar brown noise"/);assert.match(workspace,/aria-hidden="true">🔊︎<\/span>/);assert.doesNotMatch(workspace,/className="eyebrow statement-label">Enunciado/);assert.match(timer,/action === "discard_current"/);assert.match(timer,/DELETE FROM user_time_segments WHERE id=\? AND attempt_id=\? AND ended_at IS NULL/);assert.match(math,/querySelectorAll<HTMLElement>\("\.statement-section"\)/);assert.match(math,/\^Parte\\s\+/);assert.doesNotMatch(math,/labelParagraph\?\.nextElementSibling/);assert.match(math,/block\.querySelector\("\.statement-part-button"\)/);assert.match(css,/\.noise-toggle\{position:absolute/);assert.doesNotMatch(css,/\.noise-toggle::after/);assert.match(css,/\.statement-part-heading\{font-weight:700\}/)});

test("mock exams start with three problems, support editing and show honest raw-score visuals",async()=>{const [component,route,css]=await Promise.all([read("app/components/MockExams.tsx"),read("app/api/mock-exams/route.ts"),read("app/globals.css")]);assert.match(component,/\[1,2,3\]/);assert.match(component,/editingId \? "PATCH" : "POST"/);assert.match(component,/Notas brutas; as escalas podem variar/);assert.match(component,/mock-problem-bars/);assert.doesNotMatch(component,/placeholder="IPhO 2022"/);assert.match(route,/export async function PATCH/);assert.match(route,/WHERE id=\? AND owner_id=\?/);assert.match(route,/DELETE FROM user_mock_exam_problem_scores_v2/);assert.match(css,/\.mock-score-chart/)});
test("keeps the question workspace concise and fixes hint and noise controls",async()=>{const [workspace,statementRoute,imageRoute,css]=await Promise.all([read("app/components/ProblemWorkspace.tsx"),read("app/api/problems/[id]/statement/route.ts"),read("app/api/problem-images/[imageId]/route.ts"),read("app/globals.css")]);assert.match(workspace,/` · \$\{currentPart\.code\}`/);assert.match(workspace,/placeholder="Dúvida opcional"/);assert.match(workspace,/event\.key==="Enter"&&!event\.shiftKey/);assert.match(workspace,/noiseVolume/);assert.match(workspace,/gain\.gain\.value = noiseVolume/);assert.doesNotMatch(workspace,/>Enunciado ↗<|>Pontuação ↗<|className="shortcuts"/);assert.match(statementRoute,/proxyStatementImages/);assert.match(imageRoute,/\\d\{1,10\}/);assert.match(imageRoute,/contentType\.toLowerCase\(\)\.startsWith\("image\/"\)/);assert.match(css,/\.noise-volume/)});
