import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";

function database(){const db=new DatabaseSync(":memory:");db.exec(readFileSync(new URL("../db/migrations/0001_phors_catalog.sql",import.meta.url),"utf8"));db.exec(readFileSync(new URL("../db/migrations/0002_personal_training.sql",import.meta.url),"utf8"));db.exec("INSERT INTO phors_competitions (id,source_key,name,source_url,source_host) VALUES (1,'xy.pho.rs','XY','https://xy.pho.rs/','xy.pho.rs'); INSERT INTO phors_exams (id,competition_id,source_key,source_url,title,year,code,series,source_hash,imported_at) VALUES (1,1,'xy:Y25','https://xy.pho.rs/Y25','Y25',2025,'Y25','Y','x','2026-01-01'); INSERT INTO phors_problems (id,exam_id,source_id,source_url,code,title,kind,source_hash,imported_at) VALUES (1,1,'4557','https://pho.rs/p/4557','T1','Ciclos','theoretical','x','2026-01-01'); INSERT INTO phors_problem_parts (id,problem_id,source_key,code,ordinal,source_url) VALUES (1,1,'a1','A1',1,'https://pho.rs/p/4557#a1')");return db;}

test("segments accumulate initial reading and repeated item intervals",()=>{const db=database();db.prepare("INSERT INTO user_attempts (id,problem_id,status,current_state,started_at) VALUES ('a',1,'in_progress','initial_reading','2026-01-01T00:00:00.000Z')").run();db.prepare("INSERT INTO user_time_segments (id,attempt_id,state,started_at,ended_at,duration_seconds) VALUES ('s1','a','initial_reading','2026-01-01T00:00:00.000Z','2026-01-01T00:02:00.000Z',120),('s2','a','item_active','2026-01-01T00:02:00.000Z','2026-01-01T00:05:00.000Z',180),('s3','a','item_active','2026-01-01T00:06:00.000Z','2026-01-01T00:07:00.000Z',60)").run();db.prepare("UPDATE user_time_segments SET problem_part_id=1 WHERE state='item_active'").run();const rows=db.prepare("SELECT state,SUM(duration_seconds) seconds FROM user_time_segments GROUP BY state ORDER BY state").all();assert.deepEqual(rows.map((row)=>({...row})),[{state:"initial_reading",seconds:120},{state:"item_active",seconds:240}]);db.close()});

test("only explicit finish counts a question and repeats keep unique count stable",()=>{const db=database();db.exec("INSERT INTO user_attempts (id,problem_id,status,current_state,started_at) VALUES ('open',1,'in_progress','paused','2026-01-01'); INSERT INTO user_attempts (id,problem_id,status,current_state,started_at,finished_at) VALUES ('done1',1,'completed','paused','2026-01-02','2026-01-02'),('done2',1,'completed','paused','2026-01-03','2026-01-03')");const completed=db.prepare("SELECT COUNT(*) count,COUNT(DISTINCT problem_id) unique_count FROM user_attempts WHERE status='completed'").get();assert.deepEqual({...completed},{count:2,unique_count:1});assert.equal(db.prepare("SELECT COUNT(*) count FROM user_attempts").get().count,3);db.close()});

test("mock exams remain separate from isolated attempts",()=>{const db=database();db.exec("INSERT INTO user_mock_exams (id,exam_id,date,type,total_score,max_score) VALUES ('m',1,'2026-02-01','theoretical',7.5,10); INSERT INTO user_mock_exam_problem_scores (id,mock_exam_id,problem_id,score,max_score) VALUES ('ms','m',1,7.5,10)");assert.equal(db.prepare("SELECT COUNT(*) count FROM user_attempts").get().count,0);assert.deepEqual({...db.prepare("SELECT score,max_score FROM user_mock_exam_problem_scores").get()},{score:7.5,max_score:10});db.close()});
