import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";

function database(){const db=new DatabaseSync(":memory:");db.exec(readFileSync(new URL("../db/migrations/0001_phors_catalog.sql",import.meta.url),"utf8"));db.exec(readFileSync(new URL("../db/migrations/0002_personal_training.sql",import.meta.url),"utf8"));db.exec(readFileSync(new URL("../drizzle/0004_personal_training_v2.sql",import.meta.url),"utf8"));db.exec(readFileSync(new URL("../drizzle/0005_multi_user_accounts.sql",import.meta.url),"utf8"));db.exec("INSERT INTO phors_competitions (id,source_key,name,source_url,source_host) VALUES (1,'xy.pho.rs','XY','https://xy.pho.rs/','xy.pho.rs'); INSERT INTO phors_exams (id,competition_id,source_key,source_url,title,year,code,series,source_hash,imported_at) VALUES (1,1,'xy:Y25','https://xy.pho.rs/Y25','Y25',2025,'Y25','Y','x','2026-01-01'); INSERT INTO phors_problems (id,exam_id,source_id,source_url,code,title,kind,source_hash,imported_at) VALUES (1,1,'4557','https://pho.rs/p/4557','T1','Ciclos','theoretical','x','2026-01-01'); INSERT INTO phors_problem_parts (id,problem_id,source_key,code,ordinal,source_url) VALUES (1,1,'a1','A1',1,'https://pho.rs/p/4557#a1')");return db;}

test("segments accumulate repeated item intervals",()=>{const db=database();db.prepare("INSERT INTO user_attempts (id,problem_id,status,current_state,started_at) VALUES ('a',1,'in_progress','item_active','2026-01-01T00:00:00.000Z')").run();db.prepare("INSERT INTO user_time_segments (id,attempt_id,state,problem_part_id,started_at,ended_at,duration_seconds) VALUES ('s2','a','item_active',1,'2026-01-01T00:02:00.000Z','2026-01-01T00:05:00.000Z',180),('s3','a','item_active',1,'2026-01-01T00:06:00.000Z','2026-01-01T00:07:00.000Z',60)").run();assert.equal(db.prepare("SELECT SUM(duration_seconds) seconds FROM user_time_segments WHERE problem_part_id=1").get().seconds,240);db.close()});

test("discarding a running interval preserves earlier time for the item",()=>{const db=database();db.exec("INSERT INTO user_attempts (id,problem_id,status,current_state,active_part_id,started_at) VALUES ('a',1,'in_progress','item_active',1,'2026-01-01T00:00:00.000Z'); INSERT INTO user_time_segments (id,attempt_id,state,problem_part_id,started_at,ended_at,duration_seconds) VALUES ('kept','a','item_active',1,'2026-01-01T00:00:00.000Z','2026-01-01T00:02:00.000Z',120),('discarded','a','item_active',1,'2026-01-01T00:03:00.000Z',NULL,NULL)");db.prepare("DELETE FROM user_time_segments WHERE id=? AND attempt_id=? AND ended_at IS NULL").run('discarded','a');assert.equal(db.prepare("SELECT SUM(duration_seconds) seconds FROM user_time_segments WHERE attempt_id='a'").get().seconds,120);assert.equal(db.prepare("SELECT COUNT(*) count FROM user_time_segments WHERE attempt_id='a' AND ended_at IS NULL").get().count,0);db.close()});

test("only explicit finish counts a question and repeats keep unique count stable",()=>{const db=database();db.exec("INSERT INTO user_attempts (id,problem_id,status,current_state,started_at) VALUES ('open',1,'in_progress','paused','2026-01-01'); INSERT INTO user_attempts (id,problem_id,status,current_state,started_at,finished_at) VALUES ('done1',1,'completed','paused','2026-01-02','2026-01-02'),('done2',1,'completed','paused','2026-01-03','2026-01-03')");const completed=db.prepare("SELECT COUNT(*) count,COUNT(DISTINCT problem_id) unique_count FROM user_attempts WHERE status='completed'").get();assert.deepEqual({...completed},{count:2,unique_count:1});assert.equal(db.prepare("SELECT COUNT(*) count FROM user_attempts").get().count,3);db.close()});

test("independent mock exams accept a variable number of problem scores",()=>{const db=database();db.exec("INSERT INTO user_mock_exams_v2 (id,exam_name,date,type,total_score) VALUES ('m','IPhO 2022','2026-02-01','theoretical',37.5); INSERT INTO user_mock_exam_problem_scores_v2 (id,mock_exam_id,problem_number,problem_label,score) VALUES ('ms1','m',1,'Q1',8.5),('ms2','m',2,'Q2',9)");assert.equal(db.prepare("SELECT COUNT(*) count FROM user_attempts").get().count,0);assert.equal(db.prepare("SELECT COUNT(*) count FROM user_mock_exam_problem_scores_v2 WHERE mock_exam_id='m'").get().count,2);assert.equal(db.prepare("SELECT exam_name FROM user_mock_exams_v2").get().exam_name,"IPhO 2022");db.close()});

test("personal records are isolated by authenticated user id",()=>{const db=database();db.exec("INSERT INTO user_attempts(id,owner_id,problem_id,status,current_state,started_at) VALUES('a','user-a',1,'completed','paused','2026-01-01'),('b','user-b',1,'completed','paused','2026-01-01'); INSERT INTO user_mock_exams_v2(id,owner_id,exam_name,date,type,total_score) VALUES('ma','user-a','IPhO','2026-01-01','theoretical',10),('mb','user-b','APhO','2026-01-01','theoretical',20)");assert.equal(db.prepare("SELECT COUNT(*) count FROM user_attempts WHERE owner_id=?").get("user-a").count,1);assert.equal(db.prepare("SELECT exam_name FROM user_mock_exams_v2 WHERE owner_id=?").get("user-b").exam_name,"APhO");db.close()});
