import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

// Inspect only the checked-in public snapshot, never personal/production data.
const catalog = JSON.parse(readFileSync(new URL('../data/phors-catalog.json', import.meta.url), 'utf8'));
function unique(rows, field) {
  const values = rows.map(row => row[field]);
  assert.ok(values.every(value => value !== undefined && value !== null), `missing ${field}`);
  assert.equal(new Set(values).size, rows.length, `duplicate ${field}`);
  return new Set(values);
}
const exams = unique(catalog.exams, 'id');
const problems = unique(catalog.problems, 'id');
const tags = unique(catalog.tags, 'id');
unique(catalog.problems, 'source_id');
unique(catalog.problems, 'source_url');
unique(catalog.problem_parts, 'id');
assert.ok(catalog.problems.every(row => exams.has(row.exam_id)), 'orphan problem');
assert.ok(catalog.problem_parts.every(row => problems.has(row.problem_id)), 'orphan part');
assert.ok(catalog.problem_tags.every(row => problems.has(row.problem_id) && tags.has(row.tag_id)), 'orphan tag link');
assert.equal(new Set(catalog.problem_tags.map(row => `${row.problem_id}:${row.tag_id}`)).size, catalog.problem_tags.length, 'duplicate tag link');
const report = {
  source: 'data/phors-catalog.json', scope: catalog.source_scope,
  exams: catalog.exams.length, problems: catalog.problems.length,
  publicStatements: catalog.problems.filter(row => row.statement_status === 'public').length,
  authenticationRequired: catalog.problems.filter(row => row.statement_status === 'authentication_required').length,
  partRecords: catalog.problem_parts.length, tags: catalog.tags.length,
  problemTagLinks: catalog.problem_tags.length,
};
const rows = Object.entries(report).filter(([, value]) => typeof value === 'number');
const markdown = `<!-- Generated by node scripts/corpus-report.mjs --write. -->\n# Public XY corpus snapshot\n\nSource: \`${report.source}\`. Scope: ${report.scope}. These are imported records, not users or original problems authored for PhoReal.\n\n| Record | Count |\n| --- | ---: |\n${rows.map(([key, value]) => `| ${key} | ${value} |`).join('\n')}\n\nIntegrity checks: unique IDs/source URLs; no orphan problems, parts or tag links; no duplicate problem-tag links. Part records include hierarchy and are not independent questions. This report does not certify translations or external links.\n\nReproduce: \`node scripts/corpus-report.mjs\`. Refresh: \`node scripts/corpus-report.mjs --write\`. Check freshness: \`node scripts/corpus-report.mjs --check\`.\n`;
const target = new URL('../docs/CORPUS.md', import.meta.url);
const readmePath = new URL('../README.md', import.meta.url);
const readme = readFileSync(readmePath, 'utf8');
const markers = /<!-- corpus-summary:start -->[\s\S]*?<!-- corpus-summary:end -->/;
assert.ok(markers.test(readme), 'README corpus summary markers are missing');
const number = value => value.toLocaleString('en-US');
const summary = `<!-- corpus-summary:start -->\n**Public XY snapshot:** ${number(report.exams)} exams · ${number(report.problems)} problems · ${number(report.partRecords)} part records · ${number(report.tags)} tags. ${number(report.publicStatements)} public statements; ${number(report.authenticationRequired)} requires source authentication. The reproducible report checks unique IDs/source URLs and relational integrity.\n<!-- corpus-summary:end -->`;
if (process.argv.includes('--write')) {
  mkdirSync(new URL('../docs/', import.meta.url), { recursive: true });
  writeFileSync(target, markdown);
  writeFileSync(readmePath, readme.replace(markers, summary));
}
if (process.argv.includes('--check')) {
  assert.equal(readFileSync(target, 'utf8'), markdown, 'Regenerate docs/CORPUS.md');
  assert.equal(readme.match(markers)[0], summary, 'Regenerate README corpus summary');
}
console.log(JSON.stringify(report, null, 2));
